# Generated by Django 5.2.1 on 2025-06-25 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_request_receiver_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestidentityvariant',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_identity_variants', to='core.request'),
        ),
    ]
